### ISSUE TITLE
sdk/state: ingest a broadcasted transaction and create the unauthorizedCloseAgreement

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#229]
@leighmcculloch lays out options in https://github.com/stellar/experimental-payment-channels/issues/103 for handling the prevention of clearing an `unauthorizedCloseAgreement` that may be needed later

another option is in the ingest package adding logic that re-creates the close agreement from the broadcasted transaction. This way not all previous agreements have to be stored.

this _should_ be feasible with CAP40, but look into to be sure and see what the refactoring would look like

**Comment by leighmcculloch** [comment]
> another option is in the ingest package adding logic that re-creates the close agreement from the broadcasted transaction. This way not all previous agreements have to be stored.

It isn't a problem that we've lost our own signatures because we can resign the transaction, but it may be an issue that we no longer have the transaction. In theory we should be able to regenerate the transaction as we do today for all agreements, but in practice because the Stellar SDKs and XDR change over time there's no guarantee a transaction we generate today will be the same as the transaction with the same params yesterday. This is because the XDR may change, or the SDK may change how it generates the transaction if there are many ways to generate the same conceptual transaction. In #199 we're going to store copies of the txs of the agreements we have, and so there isn't much gain in not storing the agreement if we also have to store the tx.

**Comment by leighmcculloch** [comment]
I'm going to close this issue because of my comment above, it's safer to store the close agreements rather than recreate them for the same reason it is important for us to store txs we might want to submit (#199). Please reopen if I'm missing something.
