### ISSUE TITLE
sdk/state: remove initiator terminology like FromInititiator with the address of the sender escrow account

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#66]
so it's more explicit to the user, and 'initiator' terms don't leak outside the state machine

**Comment by leighmcculloch** [comment]
This is somewhat dependent on #63 because if we store the balance on payment then we'll be storing knowledge about the initiator and responder anyway.

Rather than get rid of from initiator maybe we remove initiator and responder terms from the sdk and replace with A and B.

To further obfuscate it we could also autoassign A and B based on some algorithm using the escrow addresses or their sequence numbers. 

I think we need to think about this more,but I don't think we need to do this task specifically now.

**Comment by acharb** [comment]
I actually don't remember the original reason for this ticket @leighmcculloch do you?

Was this for clarity for the user? Or for security (that a 3rd party doesn't know who the initiator is. But not sure of the security threat there)?

**Comment by leighmcculloch** [comment]
I think this was so that the term `initiator` didn't leak out of the API since that is a bit of an implementation detail. But given how we encode the payments now I don't think that is avoidable, other than through renaming Initiator/Response to A/B.

**Comment by leighmcculloch** [comment]
I don't think this is a security issue.

**Comment by acharb** [comment]
>I think this was so that the term initiator didn't leak out of the API since that is a bit of an implementation detail. But given how we encode the payments now I don't think that is avoidable, other than through renaming Initiator/Response to A/B.

ah ok. imo Initiator/Responder is clearer than A/B

Going to close for now since I don't think it's a problem atm. If when working on outside-state machine code this becomes a problem we can re-open
