### ISSUE TITLE
sdk/state: use "payments" instead of "updates" when referring to payments

### ISSUE THREAD

**Issue by acharb** [stellar/experimental-payment-channels#85]
use the term "payments" instead of "updates" when `I` and `R` are sending payments to each other. This is more descriptive of what those steps are actually doing.

Also there are steps for "updating" a channel that are different than payments, eg. updating trustlines or `O`.

Change in the code and sequence diagrams as well

**Comment by acharb** [comment]
cc @accordeiro

**Comment by leighmcculloch** [comment]
I think we're doing this. Is that right?

**Comment by accordeiro** [comment]
Yes, we're doing it in the SEP already, but I think this issue was meant to remind us to also do that in the diagrams, like replacing "Update" with "Payment" here:

https://github.com/stellar/experimental-payment-channels/blob/3d30fd6f01a0f1b65b0949eab294704524edf2e1/specifications/diagrams/sequence-diagrams/setup-update-close.txt#L20-L27
